FROM webdevops/php-nginx:8.1
LABEL Name=tesis_dashboard Version=0.0.1
RUN apt-get -y update
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
php composer-setup.php && \
php -r "unlink('composer-setup.php');" && \
mv composer.phar /usr/bin/composer
WORKDIR /var/www
ADD ./vhost.conf /etc/nginx/conf.d/default.conf
RUN chown -R www-data:www-data /var/www
